'use strict';

const product = [
    {
        "label": "Borden",
        "name": "Milk",
        "category": "dairy",
        "description": "real milk from a cow",
        "price": 4.33,
        "pack_size": "1/gal",
        "weight_value": "3",
        "weight_unit": "lbs",
        "nutrition_info": "Healthy!",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/milk.jpg",
        "vendor_id": ""
    },
    {
        "label": "Einstein",
        "name": "Bagel",
        "category": "bread",
        "description": "real bagel from a plant",
        "price": 8.26,
        "pack_size": "12/case",
        "weight_value": "5",
        "weight_unit": "lbs",
        "nutrition_info": "Bagelly!",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/bagel.jpg",
        "vendor_id": ""
    },
    {
        "label": "Starbucks",
        "name": "Coffee",
        "category": "beverages",
        "description": "real coffee from a bean",
        "price": 22.32,
        "pack_size": "24/cs",
        "weight_value": "12",
        "weight_unit": "lbs",
        "nutrition_info": "VroomVroom!",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/coffee.jpg",
        "vendor_id": ""
    },
    {
        "label": "Tyson",
        "name": "Chicken Fingers",
        "category": "poultry",
        "description": "real fingers from a chicken",
        "price": 16.99,
        "pack_size": "1 case",
        "weight_value": "10",
        "weight_unit": "lbs",
        "nutrition_info": "Chicken Fingers!",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/chicken.jpg",
        "vendor_id": ""
    },
    {
        "label": "Heinz",
        "name": "Ketchup",
        "category": "dry goods",
        "description": "real catsup from a ketchup",
        "price": 21.85,
        "pack_size": "6/case",
        "weight_value": "12",
        "weight_unit": "lbs",
        "nutrition_info": "Saucy!",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/ketchup.jpg",
        "vendor_id": ""
    },
    {
        "label": "Baker's Joy",
        "name": "Pan Coating",
        "category": "dry goods",
        "description": "Baker’s Joy® is the original brand of nonstick baking spray with flour and allows you to effectively remove baked goods from whatever baking pan you use without damaging your finished product.",
        "price": 31.17,
        "pack_size": "6/case",
        "weight_value": "72",
        "weight_unit": "oz",
        "nutrition_info": "Allergens: Contains Soy, Contains Wheat",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/BakersJoy.jpeg",
        "vendor_id": ""
    },
    {
        "label": "Landolake",
        "name": "Cheese, Extra Melt, American",
        "category": "dairy",
        "description": "Land O Lakes® Extra Melt® Cheese offers great taste and versatility with the consistency you can count on to make your dishes great, every time.",
        "price": "20.64",
        "pack_size": "1",
        "weight_value": "5",
        "weight_unit": "lb",
        "nutrition_info": "Allergens - Contains: Milk",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/EZMelt.jpeg",
        "vendor_id": ""
    },
    {
        "label": "Jaimito",
        "name": "Manchego Cheese",
        "category": "dairy",
        "description": "A fresh, Mexican style cheese made from whole cow’s milk.",
        "price": 88.60,
        "pack_size": "4/5 lb",
        "weight_value": "20",
        "weight_unit": "lbs",
        "nutrition_info": "Whole Pasteurized Grade “A” Cow Milk, salt, rennet, cheese cultures",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/Manchego.jpeg",
        "vendor_id": ""
    },
    {
        "label": "Roland",
        "name": "Mustard, French Dijon",
        "category": "dry goods",
        "description": "Roland Extra Strong Dijon Mustard is packed under French Government Supervision.",
        "price": 70.20,
        "pack_size": "2/case",
        "weight_value": "22",
        "weight_unit": "lbs",
        "nutrition_info": "Water, Mustard Seeds, Vinegar, Salt, Citric Acid",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/DijonMustard.jpeg",
        "vendor_id": ""
    },
    {
        "label": "Zerega's",
        "name": "Pasta Shells",
        "category": "dry goods",
        "description": "Medium sized shell pasta, perfect for holding onto sauces!",
        "price": "24.88",
        "pack_size": "1",
        "weight_value": "20",
        "weight_unit": "lb",
        "nutrition_info": "Contains: Gluten",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/PastaShells.jpeg",
        "vendor_id": ""
    },
    {
        "label": "Morton",
        "name": "Salt, Kosher",
        "category": "dry goods",
        "description": "Coarse kosher salt.",
        "price": 34.75,
        "pack_size": "12/case",
        "weight_value": "36",
        "weight_unit": "lbs",
        "nutrition_info": "Gluten Free",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/MortonKosherSalt.jpeg",
        "vendor_id": ""
    },
    {
        "label": "Maldon",
        "name": "Salt, Sea, Flakes",
        "category": "dry goods",
        "description": "Fine finishing salt with a great texture.",
        "price": 59.63,
        "pack_size": "12/case",
        "weight_value": "8.5",
        "weight_unit": "oz",
        "nutrition_info": "Fresh from the sea.",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/MaldonSalt.jpeg",
        "vendor_id": ""
    },
    {
        "label": "Bunge",
        "name": "Oil, Canola",
        "category": "dry goods",
        "description": "A highly refined canola oil. It is 93% saturated-fat free and contains no additives. An exceptional oil for general kitchen needs.",
        "price": 40.45,
        "pack_size": "3/1 GL",
        "weight_value": "12",
        "weight_unit": "lbs",
        "nutrition_info": "Zero Grams Trans Fat per serving.",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/CanolaOil.jpeg",
        "vendor_id": ""
    },
    {
        "label": "Jet Puff",
        "name": "Marshmallows, Mini",
        "category": "dry goods",
        "description": "This Sweet Ingredient Can Be Used To Top Dishes, Mix Into Creations, Or Melt Into A Recipe.",
        "price": 25.61,
        "pack_size": "12/1 lb",
        "weight_value": "12",
        "weight_unit": "lbs",
        "nutrition_info": "Corn Syrup, Sugar, Modified Cornstarch, Dextrose, Water, Contains Less Than 2% Of Gelatin, Tetrasodium Pyrophosphate (Whipping Aid), Natural And Artificial Flavor, Blue 1.",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/MarshmallowsMini.jpeg",
        "vendor_id": ""
    },
    {
        "label": "Nabisco",
        "name": "Graham Cracker, Honey",
        "category": "dry goods",
        "description": "NABISCO 4.8 OZ HONEY MAID GRAHAM CRACKERS 27 BOX/CARTON CASE HONEY MAID is America's #1 graham cracker brand.",
        "price": 28.92,
        "pack_size": "27/4.8 OZ",
        "weight_value": "8.5",
        "weight_unit": "lbs",
        "nutrition_info": "Allergens: Wheat, Soy.",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/GrahamCracker.jpeg",
        "vendor_id": ""
    },
    {
        "label": "Angela Mia",
        "name": "Tomatoes, Whole Peeled",
        "category": "dry goods",
        "description": "Fresh, firm, flavorful tomatoes packed in rich tomato juice are carefully selected, steam peeled and packed within hours of harvest to deliver great flavor and a bright red color.",
        "price": 40.35,
        "pack_size": "6/#10",
        "weight_value": "40",
        "weight_unit": "lbs",
        "nutrition_info": "Vine-Ripened Tomatoes, Tomato Juice, Less Than 2% Of: Salt, Calcium Chloride, Citric Acid.",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/Tomatoes.jpeg",
        "vendor_id": ""
    },
    {
        "label": "Bush",
        "name": "Beans, Great Northern",
        "category": "dry goods",
        "description": "Bush's Best Great Northern Beans are produced from clean, sound, prepared beans that are combined with a light salt brine, and thermally processed.",
        "price": 35.69,
        "pack_size": "6/#10",
        "weight_value": "40",
        "weight_unit": "lbs",
        "nutrition_info": "Prepared great northern beans, water, salt, and calcium chloride (firming agent).",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/Beans.jpeg",
        "vendor_id": ""
    },
    {
        "label": "",
        "name": "Onion, Red",
        "category": "produce",
        "description": "Whole Red Onions, locally grown.",
        "price": 37.24,
        "pack_size": "1/50LB",
        "weight_value": "50",
        "weight_unit": "lb",
        "nutrition_info": "",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/OnionRed.jpeg",
        "vendor_id": ""
    },
    {
        "label": "",
        "name": "Carrots, Orange",
        "category": "produce",
        "description": "Whole Orange Carrots, locally grown",
        "price": 65.00,
        "pack_size": "1/50LB",
        "weight_value": "50",
        "weight_unit": "lbs",
        "nutrition_info": "",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/Carrots.jpeg",
        "vendor_id": ""
    },
    {
        "label": "",
        "name": "Romaine Hearts",
        "category": "produce",
        "description": "Fresh Romaine Hearts, locally grown",
        "price": 39.45,
        "pack_size": "1/case",
        "weight_value": "18",
        "weight_unit": "lbs",
        "nutrition_info": "",
        "photo": "https://the-walk-in-bucket.s3.us-east-2.amazonaws.com/Romaine.jpeg",
        "vendor_id": ""
    },
    // {
    //     "label": "",
    //     "name": "",
    //     "category": "",
    //     "description": "",
    //     "price": "",
    //     "pack_size": "",
    //     "weight_value": "",
    //     "weight_unit": "",
    //     "nutrition_info": "",
    //     "photo": "",
    //     "vendor_id": ""
    // },
    // {
    //     "label": "",
    //     "name": "",
    //     "category": "",
    //     "description": "",
    //     "price": "",
    //     "pack_size": "",
    //     "weight_value": "",
    //     "weight_unit": "",
    //     "nutrition_info": "",
    //     "photo": "",
    //     "vendor_id": ""
    // }
]

module.exports = product